# -*- coding: utf-8 -*-
"""
Données de référence PSPM — Ministères et Autorités Contractantes.

Source : services/LISTE_PSPM_JANVIER2025_au_08122025_V2.pdf
(Liste des PSPM du 01 janvier au 08 décembre 2025, DGMP Côte d'Ivoire).
Extrait automatiquement ; consommé par seed_ministere() / seed_autorite_contractante()
dans table_parametres_models.py.

MINISTERES            : liste de (code_pspm, nom).
AUTORITES_CONTRACTANTES : { code_pspm_ministere: [noms...] }.
"""

MINISTERES = [
    (3, 'Ministère du Tourisme et des Loisirs'),
    (4, 'Ministère des Transports'),
    (10, "Ministère de l'Intérieur et de la Sécurité"),
    (11, "Ministère d'Etat, Ministère de l'Agriculture, du Développement Rural et des Productions Vivrières"),
    (13, 'Présidence de la République'),
    (15, "Ministère de l'Environnement, du Développement Durable et de la Transition Ecologique"),
    (20, "Ministère de la Justice et des Droits de l'Homme"),
    (21, 'Ministère de la Transition Numérique et de la Digitalisation'),
    (22, "Ministère de l'Enseignement Supérieur et de la Recherche Scientifique"),
    (24, 'Ministère des Eaux et Forêts'),
    (25, 'Ministère des Finances et du Budget'),
    (26, "Ministère des Mines, du Pétrole et de l'Energie"),
    (28, 'Ministère de la Culture et de la Francophonie'),
    (31, 'Ministère des Ressources Animales et Halieutiques'),
    (32, 'Ministère délégué auprès du Premier Ministre, Ministre des Sports et du Cadre de Vie, chargé des Sports et du Cadre de Vie'),
    (34, 'Commission Electorale Indépendante'),
    (35, "Ministère d'Etat, Ministère de la Défense"),
    (38, 'Ministère de la Cohésion Nationale, de la Solidarité et de la Lutte Contre la Pauvreté'),
    (40, "Ministère de la Santé, de l'Hygiène Publique et de la Couverture Maladie Universelle"),
    (42, "Ministère de la Femme, de la Famille et de l'Enfant"),
    (43, "Ministère de l'Hydraulique, de l'Assainissement et de la Salubrité"),
    (45, 'Primature et Services Rattachés (Premier Ministre, Chef du Gouvernement, Ministre des Sports et du Cadre de Vie)'),
    (46, "Ministère délégué auprès du Ministre des Affaires Etrangères, de l'Intégration Africaine et des Ivoiriens de l'Extérieur, chargé de l'Intégration Africaine et des Ivoiriens de l'Extérieur"),
    (50, "Ministère de l'Emploi et de la Protection Sociale"),
    (51, "Ministère des Affaires Etrangères, de l'Intégration Africaine et des Ivoiriens de l'Extérieur"),
    (52, "Ministère de l'Enseignement Technique, de la Formation Professionnelle et de l'Apprentissage"),
    (53, 'Ministère de la Communication'),
    (55, 'Cour des Comptes'),
    (56, "Ministère de l'Economie, du Plan et du Développement"),
    (59, "Ministère de l'Education Nationale et de l'Alphabétisation"),
    (60, "Ministère de l'Equipement et de l'Entretien Routier"),
    (63, "Ministère de la Construction, du Logement et de l'Urbanisme"),
    (64, "Ministère de la Promotion de la Jeunesse, de l'Insertion Professionnelle et du Service Civique"),
    (67, "Ministère d'Etat, Ministère de la Fonction Publique et de la Modernisation de l'Administration"),
    (69, "Ministère du Commerce et de l'Industrie"),
    (101, "Ministère du Patrimoine, du Portefeuille de l'Etat et des Entreprises Publiques"),
    (121, 'Ministère Délégué auprès du Ministère des Transports, chargé des Affaires Maritimes'),
]

AUTORITES_CONTRACTANTES = {
    3: [
        'Cabinet du Ministre du Tourisme et des Loisirs',
        'Cellule de Passation des Marchés Publics',
        'Conseil National du Tourisme',
        "Côte d'Ivoire Tourisme",
        'Direction Départementale du Tourisme Danané',
        "Direction Générale de l'Industrie Touristique et Hôtelière",
        'Direction Générale des Loisirs',
        'Direction Régionale du Tourisme du Poro (KORHOGO)',
        "Direction de l'Information, de la Digitalisation et du Développement des Startups",
        'Direction de la Communication et de la Documentation',
        'Direction de la Coopération et de la Professionnalisation (DCP)',
        'Direction de la Valorisation, de la Formation et de la Promotion des Jeux Traditionnels',
        'Direction des Activités Touristiques (DAT)',
        'Direction des Affaires Financières / Section 350',
        'Direction des Affaires Juridiques et du Contentieux',
        "Direction des Parcs de Loisirs, d'Attraction et des Jeux Numériques",
        'Direction des Ressources Humaines',
        'Direction des Services Extérieurs',
        'Direction du Guichet Unique (DGU)',
        'Inspection Generale du Ministère du Tourisme et des Loisirs',
        'Service chargé de la Gestion du Patrimoine du MTL',
    ],
    4: [
        'AAI - Autorité de Régulation du Transport Intérieur (ARTI)',
        "AIR COTE D'IVOIRE",
        'AUTORITE DE LA MOBILITE URBAINE DANS LE GRAND ABIDJAN (AMUGA)',
        'Direction Générale des Affaires Maritimes et Portuaires (DGAMP)',
        'Direction des Affaires Financières / Section 340',
        'Fonds de Développement du Transport Routier',
        'INSTITUT DE SECURITE MARITIME INTERREGIONAL (ISMI)',
        'Office de Sécurite Routière',
        "PLAN D'ACTION DE REINSTALLATION DE LA LIGNE 1 DU METRO D'ABIDJAN",
        'SOCIETE DES TRANSPORTS ABIDJANAIS (SOTRA)',
        "UNITE DE GESTION DU PROJET LIGNE 1 DU METRO D'ABIDJAN - VOLET CONTRUCTION",
    ],
    10: [
        "COMMUNE D'ABOBO",
        "COMMUNE D'ADJAME",
        "COMMUNE D'AFFERY",
        "COMMUNE D'AKOUPE",
        "COMMUNE D'ALEPE",
        "COMMUNE D'ANYAMA",
        "COMMUNE D'ASSUEFRY",
        "COMMUNE D'ATTECOUBE",
        "COMMUNE D'ODIENNE",
        "COMMUNE D'OUME",
        'COMMUNE DE ASSINIE MAFIA',
        'COMMUNE DE BAKO',
        'COMMUNE DE BASSAWA',
        'COMMUNE DE BEDIALA',
        'COMMUNE DE BEOUMI',
        'COMMUNE DE BIN-HOUYE',
        'COMMUNE DE BINGERVILLE',
        'COMMUNE DE BODOKRO',
        'COMMUNE DE BONIEREDOUGOU',
        'COMMUNE DE BOTRO',
        'COMMUNE DE BOUAKE',
        'COMMUNE DE BOUNA',
        'COMMUNE DE BROBO',
        'COMMUNE DE BUYO',
        'COMMUNE DE DABAKALA',
        'COMMUNE DE DABOU',
        'COMMUNE DE DALOA',
        'COMMUNE DE DANANE',
        'COMMUNE DE DIABO',
        'COMMUNE DE DIEGONEFLA',
        'COMMUNE DE DIKODOUGOU',
        'COMMUNE DE DIVO',
        'COMMUNE DE DJEBONOUA',
        'COMMUNE DE DJIBROSSO',
        'COMMUNE DE FACOBLY',
        'COMMUNE DE FOUMBOLO',
        'COMMUNE DE FRESCO',
        'COMMUNE DE GBELEBAN',
        'COMMUNE DE GOULIA',
        'COMMUNE DE GRABO',
        'COMMUNE DE GRAND-BEREBY',
        'COMMUNE DE GRAND-LAHOU',
        'COMMUNE DE GRAND-ZATTRY',
        'COMMUNE DE GUEYO',
        'COMMUNE DE GUIBEROUA',
        'COMMUNE DE GUINTEGUELA',
        'COMMUNE DE GUITRY',
        'COMMUNE DE HIRE',
        'COMMUNE DE JACQUEVILLE',
        'COMMUNE DE KATIOLA',
        'COMMUNE DE KONGASSO',
        'COMMUNE DE KOONAN',
        'COMMUNE DE KOUN-FAO',
        'COMMUNE DE LAKOTA',
        "COMMUNE DE M'BAHIAKRO",
        'COMMUNE DE MADINANI',
        'COMMUNE DE MAFERE',
        'COMMUNE DE MASSALA',
        'COMMUNE DE MAYO',
        'COMMUNE DE MEAGUI',
        'COMMUNE DE MINIGNAN',
        "COMMUNE DE N'DOUCI",
        'COMMUNE DE NASSIAN',
        'COMMUNE DE NIAKARAMANDOUGOU',
        'COMMUNE DE NIELLE',
        'COMMUNE DE OUANINOU',
        'COMMUNE DE OURAGAHIO',
        'COMMUNE DE SAIOUA',
        'COMMUNE DE SAKASSOU',
        'COMMUNE DE SAMATIGUILA',
        'COMMUNE DE SAN-PEDRO',
        'COMMUNE DE SASSANDRA',
        'COMMUNE DE SATAMA-SOKORO',
        'COMMUNE DE SATAMA-SOKOURA',
        'COMMUNE DE SEGUELON',
        'COMMUNE DE SEYDOUGOU',
        'COMMUNE DE SIFIE',
        'COMMUNE DE SIKENSI',
        'COMMUNE DE SOUBRE',
        'COMMUNE DE TAABO',
        'COMMUNE DE TABOU',
        'COMMUNE DE TAFIRE',
        'COMMUNE DE TANDA',
        'COMMUNE DE TENGRELA',
        'COMMUNE DE TIASSALE',
        'COMMUNE DE TIEBISSOU',
        'COMMUNE DE TIEME',
        'COMMUNE DE TORTIYA',
        'COMMUNE DE TOUBA',
        'COMMUNE DE TRANSUA',
        'COMMUNE DE VAVOUA',
        'COMMUNE DE WOROFLA',
        'COMMUNE DE YAKASSE-ATTOBROU',
        'COMMUNE DE YOPOUGON',
        'COMMUNE DE ZIKISSO',
        'COMMUNE DE ZOUKOUGBEU',
        'CONSEIL REGIONAL AGNEBY-TIASSA',
        'CONSEIL REGIONAL DE LA ME',
        'CONSEIL REGIONAL DE SAN-PEDRO',
        'CONSEIL REGIONAL DU BAFING',
        'CONSEIL REGIONAL DU GBÔKLE',
        'CONSEIL REGIONAL DU GOH',
        'CONSEIL REGIONAL DU GUEMON',
        'CONSEIL REGIONAL DU HAUT- SASSANDRA',
        'CONSEIL REGIONAL FOLON',
        'CONSEIL REGIONAL GONTOUGO',
        'CONSEIL REGIONAL HAMBOL',
        'CONSEIL REGIONAL LÔH-DJIBOUA',
        'CONSEIL REGIONAL SUD COMOE',
        'CONSEIL REGIONAL WORODOUGOU',
        'Cellule de Passation des Marchés Publics/MIS',
        "Centre de Santé de l'Ecole Nationale de Police",
        'DISTRICT AUTONOME DU BAS- SASSANDRA',
        'DISTRICT AUTONOME DU GOH DJIBOUA',
        'Direction Générale de la Décentralisation et du Développement Local (DGDDL)',
        'Direction des Affaires Financières et du Matériel (DAFM) / Section 323',
        'Direction des Etudes, de la Programmation et du Suivi-Evaluation',
        'Office National de la Protection Civile',
    ],
    11: [
        'FIRCA / PURGA 2 - FILIERE ANANAS',
        'FIRCA / PURGA 2 - FILIERE BANANE DESSERT',
        'Institut National de Formation Professionnelle Agricole',
        'LE CONSEIL HEVEA-PALMIER A HUILE',
        "PROGRAMME D'APPUI A LA SECURISATION FONCIERE RURALE (PASFOR)",
        "PROGRAMME D'APPUI AU DEVELOPPEMENT DES FILIERES AGRICOLES (PADFA)",
        'PROGRAMME DE RENFORCEMENT DE LA SECURISATION FONCIÈRE RURALE (PRESFOR)',
        'PROJET DE POLE AGRO-INDUSTRIEL DANS LA REGION DU BELIER (2PAI- BELIER)',
        "PROJET DE RENFORNCEMENT DES MOYENS DE SUBSITANCE DES PETITS EXPLOITANTS ET DES FEMMES DANS LA REGION DU N'ZI - (PREMOPEF)",
        "PROJET DE RESILIENCE DES SYSTEMES COTONNIERS DU NORD DE LA COTE D'IVOIRE (RESCO)",
        'PROJET PURGA 2 - VOLET COTON',
        "UNITE DE COORDINATION DU PROJET DE MISE EN PLACE D'UN MECANISME D'ASSURANCE RECOLTE INDICIELLE EN COTE D'IVOIRE",
    ],
    13: [
        'Autorité de Régulation de la Commande Publique',
        "BUREAU NATIONAL D'ETUDES TECHNIQUES ET DE DEVELOPPPEMENT (BNETD)",
        "Centre de Promotion des Investissements en Côte d'Ivoire",
    ],
    15: [
        "Agence Nationale de l'Environnement",
        'Centre Ivoirien de Lutte contre la Pollution',
        'Direction des Affaires Financières / Section 343',
        'Direction des Etudes, de la Planification et des Statistiques',
        'Office Ivoirien des Parcs et Réserves',
        "PROJET D'INVESTISSEMENT POUR LA RESILIENCE DES ZONES COTIERES OUEST AFRICAINES (WACA)",
    ],
    20: [
        'AGENCE DE GESTION ET DE RECOUVREMENT DES AVOIRS CRIMINELS (AGRAC)',
        'Centre National de la Documentation Juridique',
        "Conseil National des Droits de l'Homme",
        "Direction de l'Administration Pénitentiaire (DAP)",
        "Direction de l'Administratioàn Pénitentiaire (DAP)",
        'Direction de la Législation et de la Documentation (DLD)',
        'Direction de la Planification et des Statisques (DPS)',
        'Direction des Affaires Civiles Pénales (DACP)',
        'Direction des Affaires Financières / Section 325',
        "Direction des Infrastructures, de l'Equipement et de la Maintenance (DIEM)",
        'Inspection Générale des Services Judiciaires',
        'Intendance Ministère de la Justice',
        "Maison d'Arrêt et de Correction de Bondoukou",
        'PROJET DE RENFORCEMENT DE CAPACITES DES ACTEURS DE LA JUSTICE',
    ],
    21: [
        "AUTORITE DE REGULATION DES TELECOMMUNICATIONS (ARTCI)/TIC DE CÔTE D'IVOIRE",
        'Direction des Affaires financières',
        "LA POSTE DE CÔTE D'IVOIRE (PCI)",
    ],
    22: [
        'Cellule de Passation des Marchés Publics',
        "Centre Régional des Oeuvres Universitaires d'Abidjan 1",
        "Centre Régional des Oeuvres Universitaires d'Abidjan 2",
        'Centre Régional des Oeuvres Universitaires de Bouake',
        'Centre Régional des Oeuvres Universitaires de Daloa',
        'Centre Régional des Oeuvres Universitaires de Korhogo',
        'Centre Régional des Oeuvres Universitaires de Man',
        'Centre Régional des Oeuvres Universitaires de San - Pédro',
        'Centre Régional des Œuvres Universitaires de Bondoukou',
        "Centre d'Excellence Africain pour les Mines et environnement Minier",
        'Centre de Recherche Ecologique',
        'Centre de Recherche Océanologique',
        "Direction Générale de Recherche et de l'Innovation",
        'INSPECTION GENERALE',
        'Institut National Polytechnique Félix Houphouet Boigny de Yamoussoukro',
        'Université Alassane Ouattara de Bouaké',
        'Université Félix Houphouët Boigny de Cocody',
        'Université Jean Lorougnon Guédé de Daloa',
        'Université de Bondoukou',
        'Université de Man',
    ],
    24: [
        'Brigade Spéciale de surveillance et d¿Intervention',
        'Cellule de Passation des Marchés Publics/MINEF',
        'Comité technique négociation Accord Partenariat volontaire (APV/FLEGT)',
        'Direction Générale des Forêts et de la Faune',
        'Direction Générale des Ressources en Eaux',
        'Direction Générale des Ressources en EauxACQUISITION',
        'Direction Générale des Ressources en EauxCENTRAUX',
        'Direction Générale des Ressources en EauxCONSOMMABLES',
        "Direction Générale des Ressources en EauxL'ENTRETIEN",
        "Direction Générale des Ressources en EauxL'ORGANISATION",
        'Direction Générale des Ressources en EauxMATERIELS,FOURNITURES',
        'Direction Régionale des Eaux et Forêts des Lagunes (Abidjan)',
        "Direction de l'Evaluation et du Patrimoine Hydraulique",
        "Direction de l'Informatique, des Statistiques, des Archives et de la Documentation",
        "Direction de l'exploitation et des industries forestières",
        'Direction de la Faune et des Ressources Cynegetiques',
        'Direction de la Gestion des Carrières des Agents Techniques des Eaux et Forêts',
        'Direction de la Police Forestière et de la repression',
        "Direction de la Protection et de l'Amenagement des Ressources en Eaux",
        'Direction des Affaires Financières et du Patrimoine / Section 345',
        'Direction des Affaires Juridiques',
        "Direction des Etudes, de la Planification et de l'Evaluation",
        'Direction des Ressources Humaines et de la Formation',
        'Direction du cadastre forestier et du développement forestier',
        'Ecole Nationale des Eaux et Forêts',
        'Inspection Générale des Eaux et Forêts',
        'Intendance Eaux et Forêts',
        "PROGRAMME INTEGRE DE DEVELOPPEMENT ET D'ADAPTATION AU CHANGEMENT CLIMATIQUE DANS LE BASSIN DU NIGER (PIDACC/BN-CI)",
        'SOCIETE DE DEVELOPPEMENT DES FORETS (SODEFOR)',
        'Secrétariat du Comité National de Défense de la forêt et de Lutte Contre les Feux de Brousse',
        'Service de Communication (SERCOM)',
        "Zoo d'Abidjan",
    ],
    25: [
        'AUTORITE DE REGULATION DES JEUX DE HASARD (ARJH)',
        "BANQUE DE L'HABITAT DE COTE D'IVOIRE (BHCI)",
        'Cabinet du Ministre des Finances et du Budget',
        'Direction Générale des Douanes',
        'Direction Régionale des Impôts Abidjan Nord VI',
        'Direction Régionale des Impôts Bondoukou',
        'Direction Régionale des Impôts des Lacs (Yamoussoukro)',
        'Direction Régionale des Impôts des Lagunes (Abidjan Nord 2)',
        'Direction Régionale des Impôts des Montagnes (MAN)',
        'Direction Régionale des Impôts des Savanes (KORHOGO)',
        'Direction Régionale des Impôts du Bas- Cavaly (GUIGLO)',
        'Direction Régionale des Impôts du Fromager (Gagnoa)',
        'Direction Régionale des Impôts du Haut Sassandra (Daloa)',
        'Direction Régionale des Impôts du Moyen Comoé (Abengourou)',
        "Direction Régionale des Impôts du N'ZI- Comoé (Dimbokro)",
        'Direction Régionale des Impôts du Sud- Comoé (Aboisso)',
        'Direction des Affaires Financières et du Patrioine (DAFP) / Section 322',
        'Direction des Ressources Humaines MFB',
        'Direction des Services Douaniers du Port et des Services Spéciaux',
        'Service Financier du Programme Impôt',
        'Service gestion du patrimoine et suivi de la comptabilité des matières du MEF',
        'VERSUS BANK',
    ],
    26: [
        "AUTORITE NATIONALE DE REGULATION DE L'ELECTRICITE (ANARE)",
        'CI-ENERGIES / DIRECTION DES ACQUISITIONS ET MOYENS GENERAUX / Gestion des activités de reprographie',
        'CI-ENERGIES / DIRECTION DES ACQUISITIONS ET MOYENS GENERAUX / Mise à disposition de moyens communs de travail',
        'CI-ENERGIES /DIRECTION DU TRANSPORT (DTR) /Matériels et outillages techniques',
        'Cellule de Passation des Marchés Publics/Mim',
        "Direction Départementale des Mines, du Pétrole et de l'Energie de Bouna",
        "Direction Régionale des Mines, du Pétrole et de l'Energie de Bondokou",
        "Direction de l'exploitation minière semi- industrielle, Artisanale et des carrières (DEMSIAC)",
        'Direction de la Cartographie et de la Prospection Géologique',
        "Direction de la recherche et de l'exploitation minière industrielle (DREMI)",
        'Direction des Contrôles Techniques',
        'Direction du cadastre minier (DCM)',
        'Direction régionale des Mines et de la Géologie du Zanzan (Bondoukou)',
        'REGIE - FONDS MINES',
        "SOCIETE POUR LE DEVELOPPEMENT MINIER DE LA COTE D'IVOIRE (SODEMI)",
    ],
    28: [
        'Bibliothèque Nationale',
        'Cellule de Passation des Marchés Publics/MCF',
        'Direction des Affaires Financières / Section 346',
        "Lycée d'Enseignement Artistique de Yamoussoukro",
        "Palais de la Culture d'Abidjan",
    ],
    31: [
        'Direction des Affaires Financières / Section 351',
        "PROGRAMME STRATEGIQUE DE TRANSFORMATION DE L'AQUACULTURE EN COTE D'IVOIRE (PSTACI)",
        "Unité de Gestion du Programme d'appui à la gestion durable des ressources halieutiques (PAGDRH)",
        'Unité de coordination du Projet de Développement de la filière porcine(PRO- PORC)',
        'Unité de coordination du Projet de Redynamisation des Points de Débarquements Aménagés (PRO- DEBARQUEMENT)',
        "Unité de coordination du Projet de contrôle des maladies enzootiques en Côte d'Ivoire (PRO-MALADIES)",
    ],
    32: [
        'CENTRE SPORTIF CULTUREL ET DES TIC IVOIRO-COREEN ALASSANE OUATTARA (CSCTICAO)',
        'Institut National de la Jeunesse et des Sports',
        'Office Ivoirien des Sports Scolaire et Universitaire',
        'Office National des Sports',
    ],
    34: [
        'Commission Electorale Indépendante',
    ],
    35: [
        "Centre National de Coordination du Mécanisme de Réponse à l'Alerte Précoce",
        "Direction de la Santé et de l'Action Sociale des Armées",
        'Direction des Finances',
        'Direction des Ressources Humaines',
        "Direction des Télécommunications et des Systemes d'Information (D.T.S.I.)",
        'Ecole de Gendarmerie ABIDJAN',
        'Ecole de Gendarmerie de Toroguhé',
        "Hôpital Militaire d'ABIDJAN",
    ],
    38: [
        'Direction des Affaires Financières / Section 369',
        'Direction des stratégies de réduction de la pauvreté',
        'Observatoire de la Solidarité et de la Cohésion Sociale',
        'Unité de Coordination du programme PNCS',
    ],
    40: [
        'AUTORITE IVOIRIENNE DE REGULATION PHARMACEUTIQUE (AIRP)',
        "Centre Hospitalier Régional d'Agboville",
        "Centre Hospitalier Universitaire d'Angré",
        'Centre Hospitalier Universitaire de Bouaké',
        'Centre Hospitalier Universitaire de Cocody',
        'Centre Hospitalier Universitaire de Cocody CCTOS',
        'Centre Hospitalier Universitaire de Treichville',
        'Centre Hospitalier Universitaire de Yopougon',
        "Centre National d'Oncologie Médicale et de Radiothérapie Alassane Ouattara",
        "Centre National de Prévention et de Traitement de l'Insuffisance Rénale",
        'Direction de la Prospective de la Planification et des Stratégies (DPPS)',
        'Direction des Affaires Financières / Section 335',
        'Fonds National de Lutte contre le Sida',
        'GAVI POUR LE RENFORCEMENT DU SYSTEME DE SANTE PHASE 3 (RSS3)',
        "Institut National d'Hygiène Publique",
        'Institut National de la Formation des Agents de la Santé',
        'Institut National de la Sante Publique',
        'Institut Raoul Follereau',
        "Institut de Cardiologie d'Abidjan",
        "Institut de Médecine Nucléaire d'Abidjan",
        'Laboratoire National de la Santé Publique',
        'PRET SOUVERAIN PROJET HOPITAUX ABIDJAN (PS PHA)',
        'Programme Elargi de Vaccination',
        'Programme National de Lutte contre la Tuberculose',
        'Programme National de Lutte contre le Paludisme',
        'Programme National de Lutte contre le SIDA',
        "Service d'Aide Médicale d'Urgence",
    ],
    42: [
        'Complexe Social AVENUE 1 TREICHVILLE',
        'Direction Régionale du MSFFE du Tchologo (Ferkéssedougou)',
        'Direction des Affaires Financières / Section 352',
        'Orphelinat de BINGERVILLE',
        'Pouponnière YOPOUGON',
        'Unité de Coordination du Projet Programme de prise en charge des Enfants et Adolescents Vulnérables',
    ],
    43: [
        'Agence Nationale de Gestion des Déchets',
        'Direction des Stratégies, de la Plannification et des Statistiques',
        "Inspection Générale du Ministère de l'Assainissement et la Salubrité",
        "OFFICE NATIONAL DE L'ASSAINISSEMENT ET DU DRAINAGE (ONAD)",
        "Office National de l'Eau Potable (ONEP)",
        "PROJET DE PROMOTION DE L'ACCES AUX SERVICES D'ASSAINISSEMENT AUTONOME EN MILIEU URBAIN",
        "UNITE SECTORIELLE D'EXECUTION DU PROJET D'APPUI AU PROGRAMME SOCIAL DU GOUVERNEMENT - VOLET HYDRAULIQUE (USEP - PAPSGOUV - MH)",
    ],
    45: [
        "COMMISSION NATIONALE DES FRONTIERES DE COTE D'IVOIRE (CNFCI)",
        'DISTRICT AUTONOME DU DENGUELE',
        "Imprimerie Nationale de Côte d'Ivoire",
    ],
    46: [
        'Comité National de Lutte contre la Sécheresse au Sahel',
        'Direction des Affaires Financières / Section 421',
        'Service de la planification et du suivi- évaluation',
    ],
    50: [
        'Direction Générale du Travail (DGT)',
        'Direction Régionale du Travail de Divo',
        'Direction de la Lutte contre le Travail des Enfants (DLTE)',
        "Direction des Stratégies et des Programmes d'Emploi",
        'Institut National Supérieur de Formation Sociale',
    ],
    51: [
        "Cabinet du Ministre des Affaires Etrangères, de l'Intégration Africaine et des ivoiriens de l'extéreiur",
        'Cellule de Passation des marchés Publics / MAE',
        'Direction Afrique',
        'Direction Amériques et Caraïbes',
        'Direction Asie Pacifique et Océanie',
        'Direction Europe',
        'Direction Générale de la Diplomatie Economique',
        "Direction Générale des Affaires Juridiques, Consulaires et de l'Etat Civil",
        "Direction Générale des Ivoiriens de l'Extérieur (DGIE)",
        'Direction Générale des Relations Bilatérales',
        "Direction Générale du Protocole d'Etat",
        'Direction Générales des Relations Multilatérales',
        "Direction d'Aide et d'Assistance aux Réfigiés et Apatrides",
        "Direction de l'Accueil, du Cérémonial, des Accrédidations et des Audiences",
        "Direction de l'Etat Civil et des Affaires Consulaires",
        "Direction de l'ONU et des Institutions Spécialisées des Nations-Unies",
        "Direction de l'intelligence Economique et du Suivi-Evaluation",
        'Direction de la Communication et des Relations Publiques',
        'Direction de la Coopération Economique Sectorielle',
        'Direction de la Documentation, des Archives, du Courrier et de la Valise Diplomatique',
        'Direction de la Formation Continue, des Bourses et des Stages',
        'Direction de la Mobilisation des Compétences et des Ressources de la Diaspora (DMCRD)',
        'Direction de la Planification des Projets et des Statistiques',
        'Direction des Affaires Financières / Section 321',
        'Direction des Affaires Juridiques',
        'Direction des Enjeux Globaux',
        'Direction des Organisations Internationales',
        'Direction des Privilèges et des Immunités',
        'Direction des Ressources Humaines',
        "Direction des Technologies et des Systèmes d'Information",
        'Direction du Protocole et de la Logistique',
        'Inspection Générale des Affaires Etrangères',
        'Secrétariat Général',
        'Service de Gestion du Patrimoine',
        "Service de la Traduction et de l'Interprétation",
        'Service des Conférences et des Missions Internationales',
        'Service des Passeports Officiels et des Visas',
    ],
    52: [
        'CELLULE PASSATION DES MACHES PUBLICS',
        "Cabinet du Ministre de l'Enseignement Technique, de la Formation Professionnelle et de l'Apprentissage",
        'Direction des Affaires Financières / Section 334',
        "Direction des Projets, de l'Equipement et de la Maintenance",
        "Lycée d'enseignement professionnel de GAGNOA",
        'PRET SOUVERAIN-UCP PROJET EDUCATION FORMATION (ENSEIGNEMENTTECHNIQUE) - COMPOSANTE 3 : FORMATION AGRICOLE ET RURALE NON FOF',
    ],
    53: [
        'AGENCE IVOIRIENNE DE GESTION DES FREQUENCES RADIO ELECTRIQUES (AIGF)',
        'Institut des Sciences et Techniques de la Communication',
        'SOCIETE IVOIRIENNE DE TELEDIFFUSION (SIDT)',
        'UEP-ZBTIC (COMITE DE PILOTE ZONE FRANCHE)',
    ],
    55: [
        'COUR DES COMPTES',
    ],
    56: [
        "DU PROGRAMME POUR LE DEVELOPPEMENT D'UNE PRESTATION DE SERVICE INCLUSIVE (PAME/PDSI) - PART BAILLEUR",
        "Direction Générale de l'Economie",
        'Direction Régionale du Plan du Bas- Sassandra (SAN PEDRO)',
        "PROJET D'APPUI A LA MISE EN OEUVRE DU PROGRAMME POUR LE DEVELOPPEMENT D'UNE PRESTATION DE SERVICE INCLUSIVE (PAME/PDSI) -",
    ],
    59: [
        'COLLEGE MODERNE DE GBANGBEGOUINE-YATI',
        'Collège Moderne 2 Man',
        'Direction des Affaires Financières / Section 331',
        'Direction des Cantines Scolaires',
        "Inspection Générale de l'Education Nationale",
        'Lycée Mod. 1 Abobo',
        'Lycée Mod. Adzopé',
        'Lycée Mod. San-pedro',
        'PART BAILLEUR COLLEGE MODERNE DE GBANGBEGOUINE-YATI',
        'PRET SOUVERAIN-UCP PROJET EDUCATION FORMATION - COMPOSANTE : EDUCATION NATIONALE ET ALPHABETISATION',
    ],
    60: [
        'AGEROUTE / PROJET DE ROUTE DE DESENCLAVEMENT DES ZONES TRANSFRONTALIERE (PRD-ZT) PHASE 1 - SECTION BONDOUKOU - SOKO -',
        "FRONTIERE DU GHANA Direction de la Planification et de l'Evaluation",
        "OPERATION DE CURAGE ET ENTRETIEN DANS LES 10 COMMUNES DE LA VILLE D'ABIDJAN",
        "PROJET DE TRANSPORT URBAIN D'ABIDJAN (PTUA)",
        "UNITE SECTORIELLE D'EXECUTION DU PROJET D'APPUI AU PROGRAMME SOCIAL DU GOUVERNEMENT -VOLET PISTES RURALES (USEP-PAPSGOUV-",
        "UNITE SECTORIELLE D'EXECUTION DU PROJET D'APPUI AU PROGRAMME SOCIAL DU GOUVERNEMENT -VOLET PISTES RURALES (USEP-PAPSGOUV- MEER)",
    ],
    63: [
        'Direction des Affaires Financières / Section 358',
        "Guichet Unique du Foncier et de l'Habitat",
        'MEER) Direction de la Construction et de la Maintenance',
        "Service de la Brigade d'Investigation et du Contrôle Urbain",
    ],
    64: [
        'Agence Emploi Jeunes',
        "Direction de l'Autonomisation des Jeunes et de l'Insertion Professionnelle (DAJIP)",
        "Inspection générale du Ministère de la Promotion de la Jeunesse et de l'Emploi des Jeunes",
        'Office du Service Civique National',
        'Service Informatique MPJEJ',
    ],
    67: [
        'Cellule de Passation des Marchés Publics',
        "Centre d'Education à Distance de Côte d'Ivoire",
        'Conseil de Discipline',
        'Direction Génerale de la transformation du service public',
        'Direction Régionale de la Fonction Publique du Loh-Djiboua (Divo)',
        "Direction de La Modernisation de l'Organisation Administrative (DMOA)",
        "Direction de l'Appui à la Performance du Service Public",
        'Direction de la Communication et des Relations Publiques MFP',
        'Direction de la Coordination et du Suivi des services Exterieurs',
        "Direction de la Qualité et de l'Accompagnement du Changement",
        'Direction des Affaires Juridiques et du contentieux',
        'Direction des Etudes et Méthodes',
        'Direction des Ressources Humaines',
        "Ecole Nationale d'Administration",
        'Inspection générale de la Fonction Publique',
        'Service de Gestion du Patrimoine',
    ],
    69: [
        "Cabinet du Ministre du Commerce et de l'Industrie",
        'DIRECTION REGIONALE DU COMMERCE DJIBOUA',
        "Direction de l'Encadrement, de la Promotion de l'Artisanat et de la Mutualité DPAM",
        'Direction des Affaires Financières et du Patrimoine / Section 347',
        'Direction des Infrastructures et des Sites Artisanaux',
        "Générale de l'Industrie (DGI)",
        'Générale du Commerce Intérieur',
        "Laboratoire National d'Essais, de Qualité, de Métrologie et d'Analyse",
        "Office d'Aide à la Commercialisation des Produits Vivriers",
        "PROGRAMME DIVERSIFICATION ACCELERATION INDUSTRIELLE COMPETITIVITE ET EMPLOIS / COTE D'IVOIRE PME (CIPME-DAICE)",
        'PROGRAMME DIVERSIFICATION ACCELERATION INDUSTRIELLE COMPETITIVITE ET EMPLOIS / SOCIETE DE GESTION ET DE DEVELOPPEMENT DES INFRASTRUCTURES INDUSTRIELLES (SOGEDI-DAICE)',
        'UNITE DE GESTION DU PROGRAMME DIVERSIFICATION ACCELERATION INDUSTRIELLE COMPETITIVITE ET EMPLOIS (UGP-DAICE)',
    ],
    101: [
        "SOCIETE NATIONALE DE GESTION DU PATRIMOINE IMMOBILIER DE L'ETAT (SONAPIE)",
    ],
    121: [
        'Direction Générale des Affaires Maritimes et Portuaires (DGAMP)',
        'Direction des Affaires Financières',
    ],
}
